<!DOCTYPE html>
<html lang="en">
    <head>
	<meta charset="utf-8">
	<title>Zend Demo Site</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    
	<link rel="stylesheet" href="/themes/simplex/css/bootswatch.min.css">
	<link rel="stylesheet" href="/themes/simplex/css/bootstrap.css">
	<link rel="stylesheet" href="/styles/main.css">

    </head>
    <body>
	<header>
	    <div class="navbar navbar-default navbar-fixed-top">
		<div class="container">
		    <div class="navbar-header">
			<a href="/" class="navbar-brand">Zend Demo</a>
			<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
			</button>
		    </div>
		<div class="navbar-collapse collapse" id="navbar-main">
		    <ul class="nav navbar-nav navbar-right">
			<li><a href="//github.com/splicefracture/zend_demo" >source</a></li>
			<li><a href="//splicefracture.com/" >splice:fracture</a></li>
		    </ul>
		</div>
	    </div>
	</header>
	<div id="content">
	    <?php echo $this->layout()->content ?>
	</div>
    
	<script type="text/javascript" src="/js/underscore.min.js"></script>
	<script type="text/javascript" src="/js/underscore.string.min.js"></script>
	<script type="text/javascript" src="/js/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="/js/backbone.js"></script>

        <script type="text/javascript" src="scripts/main.js"></script>
        <script type="text/javascript" src="scripts/models/restaurant.js"></script>
        <script type="text/javascript" src="scripts/views/search.js"></script>
	<script type="text/javascript" src="scripts/views/menu.js"></script>
        <script type="text/javascript" src="scripts/collections/menu.js"></script>
        
    </body>
</html>



