<?php
// This file generated by Propel 1.7.1 convert-conf target
return array (
  'BaseCuisine' => 'site/om/BaseCuisine.php',
  'BaseCuisinePeer' => 'site/om/BaseCuisinePeer.php',
  'BaseCuisineQuery' => 'site/om/BaseCuisineQuery.php',
  'BaseRestaurant' => 'site/om/BaseRestaurant.php',
  'BaseRestaurantPeer' => 'site/om/BaseRestaurantPeer.php',
  'BaseRestaurantQuery' => 'site/om/BaseRestaurantQuery.php',
  'Cuisine' => 'site/Cuisine.php',
  'CuisinePeer' => 'site/CuisinePeer.php',
  'CuisineQuery' => 'site/CuisineQuery.php',
  'CuisineTableMap' => 'site/map/CuisineTableMap.php',
  'Restaurant' => 'site/Restaurant.php',
  'RestaurantPeer' => 'site/RestaurantPeer.php',
  'RestaurantQuery' => 'site/RestaurantQuery.php',
  'RestaurantTableMap' => 'site/map/RestaurantTableMap.php',
);