<?php
// This file generated by Propel 1.7.1 convert-conf target
// from XML runtime conf file /var/www/application/configs/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'site' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'classname' => 'PropelPDO',
        'dsn' => 'mysql:host=localhost;dbname=site',
        'user' => 'root',
        'password' => 'devpass1',
      ),
    ),
    'default' => 'site',
  ),
  'generator_version' => '1.7.1',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-site-conf.php');
return $conf;